# Generated by Django 2.0.1 on 2020-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20200130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemsdopedido',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
