# Generated by Django 2.0.1 on 2020-02-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20200131_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('permissao2', 'Permissao 2'), ('permissao3', 'Permissao 3'))},
        ),
    ]
