# Generated by Django 2.0.1 on 2020-02-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20200203_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissao 3'))},
        ),
    ]
