# Generated by Django 2.0.1 on 2020-01-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20200130_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdopedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemsdopedido',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItemsDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
