# Generated by Django 2.0.1 on 2020-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20200130_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Usuario pode deletar clientes'),)},
        ),
    ]
